package com.sponsorship.tests.payment;

import com.sponsorship.base.BaseTest;
import org.testng.Assert;
import org.testng.SkipException;
import org.testng.annotations.Test;

/**
 * PaymentTests - Automation tests for the Payment Processing module.
 * Test Cases: TC_05_01 - TC_05_06
 */
public class PaymentTests extends BaseTest {

    // ============================================================
    // TC_05_01 - Verify payment auto-creation upon work completion
    // ============================================================

    @Test(description = "TC_05_01 - Payment auto-creation in PENDING status",
            groups = {"regression", "payment"})
    public void TC_05_01_paymentAutoCreation() {
        createTest("TC_05_01", "Payment auto-creation upon work completion");
        getTest().info("Note: True end-to-end requires driving a campaign from creation to completion. Validating PENDING payments exist.");
        loginAsBrand();
        navbar.goToPayments();

        getTest().info("Verify PENDING payments exist in the table");
        java.util.List<String> statuses = paymentPage.getPaymentStatuses();
        boolean hasPending = statuses.stream().anyMatch(s -> s.equalsIgnoreCase("Pending"));
        
        if (hasPending) {
            getTest().pass("Found PENDING payments automatically generated by system.");
        } else {
            getTest().skip("No PENDING payments found. Cannot verify auto-creation without full E2E setup.");
        }
    }

    // ============================================================
    // TC_05_02 - Verify brand can confirm pending payment
    // ============================================================

    @Test(description = "TC_05_02 - Brand can process and confirm payment",
            groups = {"smoke", "regression", "payment"})
    public void TC_05_02_confirmPendingPayment() {
        createTest("TC_05_02", "Confirm pending payment");
        loginAsBrand();
        navbar.goToPayments();

        if (!paymentPage.hasCompleteButton()) {
            getTest().skip("No pending payments available to complete");
            throw new SkipException("No pending payments");
        }

        getTest().info("Step 1: Click Complete on the first pending payment");
        paymentPage.completeFirstPayment();

        getTest().info("Step 2: Verify success message");
        String snackbarText = paymentPage.getSnackbarText();
        Assert.assertTrue(snackbarText.toLowerCase().contains("success") || 
                          snackbarText.toLowerCase().contains("complet"),
                "Should show success message on completion");

        getTest().pass("Payment confirmed successfully");
    }

    // ============================================================
    // TC_05_03 - Verify payment filtering (BLOCKED)
    // ============================================================

    @Test(description = "TC_05_03 - BLOCKED: Status filter not implemented",
            groups = {"regression", "payment"}, enabled = true)
    public void TC_05_03_paymentFiltering() {
        createTest("TC_05_03", "BLOCKED: Payment filtering by status");
        getTest().warning("Feature NOT IMPLEMENTED: The payments page has no filter dropdown.");
        getTest().skip("BLOCKED - Feature Not Implemented: Payment filtering");
        throw new SkipException("BLOCKED - TC_05_03: Payment filtering not implemented");
    }

    // ============================================================
    // TC_05_04 - Verify downloading payment receipts (BLOCKED)
    // ============================================================

    @Test(description = "TC_05_04 - BLOCKED: Download receipt not implemented",
            groups = {"regression", "payment"}, enabled = true)
    public void TC_05_04_downloadReceipt() {
        createTest("TC_05_04", "BLOCKED: Download payment receipt");
        getTest().warning("Feature NOT IMPLEMENTED: No download buttons exist for payments.");
        getTest().skip("BLOCKED - Feature Not Implemented: Download receipt");
        throw new SkipException("BLOCKED - TC_05_04: Download receipt not implemented");
    }

    // ============================================================
    // TC_05_05 - Verify double payment prevention
    // ============================================================

    @Test(description = "TC_05_05 - Double payment prevention",
            groups = {"regression", "payment"})
    public void TC_05_05_preventDoublePayment() {
        createTest("TC_05_05", "Double payment prevention");
        getTest().info("Verify UI logic - completed payments don't have Complete button");
        
        loginAsBrand();
        navbar.goToPayments();

        int totalRows = paymentPage.getPaymentRowCount();
        int completeButtons = paymentPage.getCompleteButtonCount();
        
        // If there are completed payments, the number of Complete buttons should be less than total rows
        if (totalRows > 0 && paymentPage.getPaymentStatuses().contains("Completed")) {
            Assert.assertTrue(completeButtons < totalRows, 
                "Completed payments should not have a Complete button to prevent double processing");
            getTest().pass("Completed payments correctly disable/hide the processing button");
        } else {
            getTest().skip("No completed payments available to verify logic");
        }
    }

    // ============================================================
    // TC_05_06 - Verify influencer dashboard updates total earnings
    // ============================================================

    @Test(description = "TC_05_06 - Influencer dashboard updates total earnings",
            groups = {"regression", "payment"})
    public void TC_05_06_influencerDashboardEarnings() {
        createTest("TC_05_06", "Influencer dashboard updates total earnings");
        loginAsInfluencer();
        
        getTest().info("Step 1: Check Total Earnings metric on dashboard");
        String earningsStr = influencerDashboard.getTotalEarnings();
        Assert.assertNotNull(earningsStr, "Earnings should not be null");
        
        // Check if it parses as a number (removing $ and commas)
        try {
            String cleanNumber = earningsStr.replaceAll("[^0-9.]", "");
            double earnings = Double.parseDouble(cleanNumber);
            getTest().pass("Dashboard correctly calculates and displays earnings metric: " + earningsStr);
        } catch (NumberFormatException e) {
            Assert.fail("Earnings is not a valid number format: " + earningsStr);
        }
    }
}
